### ISSUE TITLE
🎯 카카오 로그인 구현

### ISSUE THREAD

**Issue by tastekim** [U-Wreckcar/U-wreckcar-BE#6]
# 목표
- [x] 카카오 API 연결하기
- [x] 유저 로그인 창 연결하기
- [ ] #9
- [ ] 유저 정보 가져오기
- [ ] 메인 페이지로 redirect

## 추가 내용

1. 서버 쪽에서만 구현해보려 했는데 프론트랑 같이 맞춰야 하는 부분이 생김.
2. 카카오 닉네임을 제외한 나머지 유저 정보는 필수값이 아닌데 카카오 이메일이 필수값 설정이 안된다. 로그인 후에 유저정보에서 넘어오는 reponse 값에 어떤 값들이 들어오는지 확인해봐야겠다.
![스크린샷 2023-03-02 오전 4 45 46](https://user-images.githubusercontent.com/112174727/222248402-3541091d-dbeb-448b-a1e9-92da4b5008ff.png)

**Comment by rtg1014** [comment]
![사진 1](https://user-images.githubusercontent.com/105336416/222349681-93f00030-133c-4a50-bc0c-0e823442b017.PNG)

실제 이메일 값을 받을수는 없지만 이런식으로 이메일을 대체할 값을 받을 수는 있습니다.
다만 실제 이메일을 주지는 않는것 같아요

![이메일 사진 1](https://user-images.githubusercontent.com/105336416/222350082-dd8f37d0-ab7c-4263-91f7-4353dd623dfc.PNG)

2번째 사진은 위 항목대로 받게 될시  db 에 저장했던 제 프로젝트 예시 입니다
이 루트로 하는건 어떨까요?
